apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-dev-cert
  namespace: fastapi-dev
spec:
  secretName: tls-dev-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fastapi_dev.laurenthoarau.cloud-ip.cc
  duration: 4320h                  # 180 jours à partir du 02 Avril 2026
  renewBefore: 720h                # Renouveler 30j avant expiration
