apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-staging-cert
  namespace: fastapi-staging
spec:
  secretName: tls-staging-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - fastapi_staging.laurenthoarau.cloud-ip.cc
  duration: 4320h                          # 180 jours à partir du 02 Avril 2026
  renewBefore: 720h                        # Renouveler 30 jours avant
