apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-prod

resources:
  - ../../base
  - namespace.yaml
  - certificate.yaml
  - middleware-auth.yaml

patches:
  - path: patches/configmap.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: backend
  - path: patches/ingressroute.yaml
    target:
      kind: IngressRoute
      name: app-ingress

images:
  - name: maclorenzy/fastapi-backend
    newTag: prod-latest
  - name: maclorenzy/fastapi-frontend
    newTag: prod-latest
```

---
