apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: dev
    project: fastapi-fullstack
spec:
  project: default
  source:
    repoURL: https://github.com/Maclorenzy/FastAPI_k8s
    targetRevision: master
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  info:
    - name: URL
      value: https://fastapi_dev.laurenthoarau.cloud-ip.cc
